name: Deploy1

on:
  push:
    paths:
      - .github/workflows/main.yml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "soto795" --password-stdin
        docker image build -t soto795/declutternode:v1 .
        docker push soto795/declutternode:v1
